server:
  port: 8761

spring:
  application:
    name: SERVICE-REGISTRY

eureka:
  instance:
    hostname: 192.168.0.227
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
