# docker run -d -rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo

version: '3.8'

services:

  config-server:
    image: smjaknis/config-server
    container_name: config-server
    ports:
      - 9296:9296
    volumes:
      - configserver:/data/configserver
volumes:
  configserver: